avatar:
  url: /images/avatar.png
  rounded: true
  opacity: 1

banner:
  enable: true
  title: 臭臭の小站
  src: /js/ui/banner.js
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

social:
  #  - name: QQ
  #    link: https://ti.qq.com/open_qq/index2.html?url=mqqapi%3a%2f%2fuserprofile%2ffriend_profile_card%3fsrc_type%3dweb%26version%3d1.0%26source%3d2%26uin%3d3285956207
  #    icon: icon-qq-line
  #    color: "#12B7F5"
  - name: GitHub
    link: https://github.com/ssmzhn
    icon: icon-github-line
    color: "#6e5494"
#  - name: 微博
#    link: https://weibo.com/jizhideyunyoujun
#    icon: icon-weibo-line
#    color: "#E6162D"
#  - name: 豆瓣
#    link: https://www.douban.com/people/yunyoujun/
#    icon: icon-douban-line
#    color: "#007722"
  - name: 网易云音乐
    link: http://music.163.com/m/user/home?id=1790526375
    icon: icon-netease-cloud-music-line
    color: "#C20C0C"
  - name: 知乎
    link: https://www.zhihu.com/people/she-sha-ming-zi-hao-ni/
    icon: icon-zhihu-line
    color: "#0084FF"
  - name: 哔哩哔哩
    link: https://b23.tv/n2PyuM
    icon: icon-bilibili-line
    color: "#FF8EB3"
  # - name: POPI
  #   link: https://www.popiapp.cn/elpsycn
  #   icon: icon-questionnaire-line
  #   color: "#525252"
  #  - name: 微信公众号
  #    link: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/about/white-qrcode-and-search.jpg
  #    icon: icon-wechat-2-line
  #    color: "#1AAD19"
  - name: Twitter
    link: https://twitter.com/ssmzhn12138
    icon: icon-twitter-line
    color: "#1da1f2"
  - name: Telegram
    link: https://t.me/NameSetter
    icon: icon-telegram-line
    color: "#0088CC"
  #  - name: Telegram Channel
  #    link: https://t.me/elpsycn
  #    # icon: icon-telegram-fill
  #    icon: icon-telegram-line
  #    color: "#0088CC"
  - name: E-Mail
    link: mailto:ssmzhn@163.com
    icon: icon-mail-line
    color: "#8E71C1"
      #  - name: Travelling
      #    link: https://travellings.link
      #    icon: icon-train-line
      #    color: black
reward:
  enable: false
pages:
  - name: 小伙伴们
    url: /links
    icon: icon-genderless-line
    color: dodgerblue
notice:
  enable: true
  content: 来了就看看再走吧！
comment:
  enable: true
  tips:
    - 若您想及时得到回复提醒，建议跳转 GitHub Issues 评论。
    - 若没有本文 Issue，您可以使用 Comment 模版新建。
  candidates:
#    - valine
    - utterances
utterances:
  enable: true
#  src: https://utteranc.es/client.js
  repo: ssmzhn/ssmzhn.github.io
  issue-term: pathname
  # label: comment
  theme: github-light
#  crossorigin: anonymous

#<script src="https://utteranc.es/client.js"
#        repo="ssmzhn/ssmzhn.github.io"
#        issue-term="pathname"
#        theme="github-light"
#        crossorigin="anonymous"
#        async>
#</script>
footer:
  since: 2021
  live_time:
    enable: true
    prefix: 这个博客爬了
    suffix: 😅
    start_time: "2021-08-15T17:23:40"

wordcloud:
  enable: true

codeblock:
  copy_btn: true
katex:
  copy_tex: true
  global: false

#默哀
mourn:
  enable: true
  days:
    - "4-5"
    - "12-13"
    - "9-18"
    - "5-12"

head:
  css:
    fonts: 
      - https://fonts.loli.net/css?family=Saira
      - https://fonts.loli.net/css?family=JetBrains%20Mono

font:
  cdn:
    enable: true
    lib:
      - https://fonts.loli.net/css?family=Saira
      - https://fonts.loli.net/css?family=JetBrains%20Mono
  serif:
    family: '''Songti SC'', ''Noto Serif SC'', STZhongsong, STKaiti, KaiTi, Roboto, serif'
    weight: 900
  sans_serif:
    family: 'Saira, ''PingFang SC'', ''Microsoft YaHei'', Roboto, Arial, sans-serif'
    weight: 400
  monospace:
    family: '''JetBrains Mono'', ''Source Code Pro'', ''Courier New'', Courier, Consolas, Monaco, monospace'

